---
name: tests

on:
  push:
    branches-ignore:
    - 'development/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '8'
        cache: 'npm'
    - name: install dependencies
      run: npm install
    - name: audit installed packages
      run: npm audit
      continue-on-error: true # TODO: Fix audit report
    - name: lint
      run: npm run lint
    - name: unit, functional tests with coverage
      run: npm run coverage

